name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - "api-doc"
      - "api-doc-*"
  pull_request:
    branches:
      - "api-doc"
      - "api-doc-*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) リポジトリをチェックアウト
      - name: Check out
        uses: actions/checkout@v3

      # 2) ブランチ名を取得
      - name: Get branch name
        id: get_branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      # 3) (必要に応じて) swagger-ui-dist のビルド or 静的ファイルコピー等
      #    今回は特にビルドをしない例として省略

      # 4) gh-pagesブランチにデプロイ
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs            # 公開対象(例: docsフォルダ内に index.html, openapi.yaml など)
          destination_dir: ${{ steps.get_branch.outputs.BRANCH_NAME }}
          publish_branch: gh-pages
